services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      # - NODE_ENV=${ENVIRONMENT}
      - DOMAIN=${DOMAIN}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # - NODE_ENV=${ENVIRONMENT}
      - DOMAIN=${DOMAIN}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 